# Generated by Django 5.0.4 on 2024-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_of_receiver_address_receiver_name'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='user_saves', to='shop.product'),
        ),
    ]
