# Generated by Django 5.0.6 on 2024-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('Criticism', 'criticism'), ('Proposal', 'proposal'), ('Report', ' report')]),
        ),
    ]
