# Generated by Django 5.0.6 on 2024-06-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_rename_first_name_order_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
