# Generated by Django 5.0.6 on 2024-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_remove_order_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
