# Generated by Django 5.0.6 on 2024-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_order_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', ' در حال پردازش '), ('Sending', 'درحال ارسال'), ('Received', 'دریافت شده'), ('Rejected', 'مرجوع')], default=1),
            preserve_default=False,
        ),
    ]
