# Generated by Django 5.0.6 on 2024-06-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('None', 'خالی'), ('Processing', ' در حال پردازش '), ('Sending', 'درحال ارسال'), ('Received', 'دریافت شده'), ('Rejected', 'مرجوع')], default='None'),
        ),
    ]
