# Generated by Django 5.0.6 on 2024-06-27 18:09

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import ordering.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_alter_order_status'),
        ('shop', '0002_alter_product_discount_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('None', 'خالی'), ('Processing', ' در حال پردازش '), ('Sending', 'درحال ارسال'), ('Received', 'دریافت شده')], default='None'),
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.BooleanField(default=False)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejects', to='shop.product')),
                ('rejecter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('file', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=ordering.models.image_sorter)),
                ('rejected_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ordering.reject')),
            ],
            options={
                'ordering': ['title', '-created'],
            },
        ),
        migrations.AddIndex(
            model_name='reject',
            index=models.Index(fields=['-created'], name='ordering_re_created_a88c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['title'], name='ordering_im_title_071464_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='ordering_im_created_4e3b2a_idx'),
        ),
    ]
