# Generated by Django 5.0.6 on 2024-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_alter_order_status_reject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reject',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
