# Generated by Django 5.0.6 on 2024-06-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0010_reject_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reject',
            name='description',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
