# Generated by Django 5.0.4 on 2024-05-28 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_rate_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='shop_commen_create_2b97b5_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create',
            new_name='created',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='shop_commen_created_6d2722_idx'),
        ),
    ]
