# Generated by Django 5.0.6 on 2024-05-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_count',
        ),
    ]
